version: "3.2"
volumes:
  data:
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
      POSTGRES_DB: customer
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - customer-network
  app:
    build: 
      context: .
    environment: 
      DATABASE_URL: ecto://customer:customer@postgres/customer
      MIX_ENV: prod
      SECRET_KEY_BASE: f6aAUY2EqDEZE/7esccIXhzl3Q9hzWnWctqI0MtdlenTlP22OsdfErplPjQ2L2PT
    mem_limit: 500m
    cpus: 3
    ports: 
      - 80:4000
    networks: 
      - customer-network

networks:
    customer-network:
        driver: bridge